/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:31ed300a-4334-4b2c-9a99-c972a2e683e6",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Da3NftLFu",
    "aws_user_pools_web_client_id": "68c1b0vhh58pc9pdqpvkfuhvh3",
    "oauth": {},
    "aws_user_files_s3_bucket": "amplify-weddingsite-dev-231433-deployment",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
